<?php

namespace Quatrebarbes\Larchiclass\Generators;

class PlantUmlGenerator
{
    /**
     * Generate a PlantUML diagram string from analyzed class data.
     */
    public function generate(array $classes): string
    {
        $lines = [
            '@startuml',
            '',
            "' Generated by LarchiClass - " . now()->toDateTimeString(),
            "' https://github.com/quatrebarbes/larchiclass",
            '',
            "'!pragma layout smetana",
            '!pragma useIntermediatePackages false',
            'set separator \\ ',
            'left to right direction',
            '',
            'skinparam classAttributeIconSize 0',
            'skinparam classFontStyle Bold',
            'skinparam classBackgroundColor #F8F9FA',
            'skinparam classBorderColor #6C757D',
            'skinparam arrowColor #495057',
            'skinparam groupInheritance 2',
            '',
            "' Stereotype styles",
            'skinparam class {',
            '    BackgroundColor<<model>> #D8F3DC',
            '    BorderColor<<model>> #52B788',
            '    BackgroundColor<<vendor>> #E9ECEF',
            '    BorderColor<<vendor>> #ADB5BD',
            '    FontColor<<vendor>> #6C757D',
            '}',
            '',
            'hide empty members',
            '',
        ];

        $lines[] = "' -- Application classes -----------------------------";
        foreach ($classes as $class) {
            $lines[] = $this->renderClassBlock($class);
        }

        $structuralRelations = $this->renderStructuralRelations($classes);
        if (! empty($structuralRelations)) {
            $lines[] = '';
            $lines[] = "' -- Structural relations (extends / implements / uses) --";
            array_push($lines, ...$structuralRelations);
        }

        $eloquentRelations = $this->renderEloquentRelations($classes);
        if (! empty($eloquentRelations)) {
            $lines[] = '';
            $lines[] = "' -- Eloquent relationships --------------------------";
            array_push($lines, ...$eloquentRelations);
        }

        $lines[] = '';
        $lines[] = '@enduml';

        return implode(PHP_EOL, $lines) . PHP_EOL;
    }

    // -------------------------------------------------------------------------
    // Protected helpers
    // -------------------------------------------------------------------------

    protected function renderClassBlock(array $class): string
    {
        $keyword = match (true) {
            $class['isInterface'] => 'interface',
            $class['isAbstract']  => 'abstract class',
            $class['isEnum']      => 'enum',
            default               => 'class',
        };

        $stereotypes = array_filter([
            $class['isTrait']    ? '<<trait>>'  : null,
            $class['isEloquent'] ? '<<model>>'  : null,
            $class['isVendor']   ? '<<vendor>>' : null,
        ]);
        $stereotype = $stereotypes ? ' ' . implode(' ', $stereotypes) : '';

        $lines = ["{$keyword} {$class['fqcn']}{$stereotype} {"];

        foreach ($class['properties'] as $prop) {
            $visibility = $this->visibilitySymbol($prop['visibility']);
            $static     = $prop['static'] ? '{static} ' : '';
            $type       = $prop['type'] ? ' : ' . $this->escapeType($prop['type']) : '';
            $lines[]    = "    {field}{$visibility}{$static}{$prop['name']}{$type}";
        }

        $methods = $class['methods'] ?? [];
        foreach ($methods as $method) {
            $visibility = $this->visibilitySymbol($method['visibility']);
            $static     = $method['static']   ? '{static} '   : '';
            $abstract   = $method['abstract'] ? '{abstract} ' : '';
            $lines[]    = "    {method}{$visibility}{$abstract}{$static}{$method['name']}";
        }

        $lines[] = '}';
        $lines[] = '';

        return implode(PHP_EOL, $lines);
    }

    protected function renderStructuralRelations(array $classes): array
    {
        $lines = [];

        $whiteListedFqcn = array_column($classes, 'fqcn');

        foreach ($classes as $class) {
            $fqcn = $class['fqcn'];

            if ($class['parent'] && in_array($class['parent'], $whiteListedFqcn)) {
                $lines[] = "{$class['parent']} <|-- {$fqcn}";
            }

            foreach ($class['interfaces'] as $iface) {
                if (in_array($iface, $whiteListedFqcn)) {
                    $lines[] = "{$iface} <|.. {$fqcn}";
                }
            }

            foreach ($class['traits'] as $trait) {
                if (in_array($trait, $whiteListedFqcn)) {
                    $lines[] = "{$trait} <.. {$fqcn} : <<uses>>";
                }
            }

            foreach ($class['dependencies'] ?? [] as $dep) {
                if (in_array($dep, $whiteListedFqcn)) {
                    $lines[] = "{$fqcn} ..> {$dep} : <<uses>>";
                }
            }
        }

        return $lines;
    }

    /**
     * Render Eloquent relationship arrows, merging reciprocal pairs into one link.
     *
     * When two models declare inverse relations (e.g. User hasMany Post and Post
     * belongsTo User), a single arrow is emitted with both labels stacked, and the
     * cardinality is taken from the "has" side.
     *
     * PlantUML arrow cardinality:
     *   hasOne / hasOneThrough     →  "1" – "0..1"
     *   hasMany / hasManyThrough   →  "1" – "*"
     *   belongsTo                  →  "*" – "1"
     *   belongsToMany              →  "*" – "*"
     *   morphOne                   →  "1" – "0..1"
     *   morphMany                  →  "1" – "*"
     *   morphTo                    →  dashed, polymorphic
     *   morphToMany / morphedByMany→  "*" – "*"
     */
    protected function renderEloquentRelations(array $classes): array
    {
        $lines      = [];

        $edges      = [];
        $morphEdges = [];

        $whiteListedFqcn = array_column($classes, 'fqcn');

        foreach ($classes as $class) {
            foreach ($class['relations'] ?? [] as $rel) {
                if ($rel['kind'] === 'morphTo' || $rel['related'] === '*') {
                    $morphEdges[] = ['source' => $class['fqcn'], 'rel' => $rel];
                    continue;
                }

                $targetName = ($rel['relatedFqcn'] && in_array($rel['relatedFqcn'], $whiteListedFqcn))
                    ? $rel['relatedFqcn']
                    : $rel['related'];

                $edges[] = ['source' => $class['fqcn'], 'target' => $targetName, 'rel' => $rel];
            }
        }

        // Group edges by unordered pair {A, B} to detect reciprocal relations
        $buckets = [];
        foreach ($edges as $edge) {
            $pair = [$edge['source'], $edge['target']];
            sort($pair);
            $buckets[implode('|', $pair)][] = $edge;
        }

        $hasSideKinds = ['hasOne', 'hasMany', 'hasOneThrough', 'hasManyThrough',
                         'morphOne', 'morphMany', 'morphToMany', 'morphedByMany',
                         'belongsToMany'];

        foreach ($buckets as $bucket) {
            if (count($bucket) === 1) {
                $e = $bucket[0];
                [$sc, $tc] = $this->cardinalityFor($e['rel']['kind']);
                $lines[] = "{$e['source']} \"{$sc}\" -- \"{$tc}\" {$e['target']} : {$this->relationLabel([$e['rel']])}";
                continue;
            }

            // Pick the "has" side as the primary edge for cardinality
            $primary = null;
            foreach ($bucket as $e) {
                if (in_array($e['rel']['kind'], $hasSideKinds, true)) {
                    $primary = $e;
                    break;
                }
            }
            $primary ??= $bucket[0];

            [$sc, $tc] = $this->cardinalityFor($primary['rel']['kind']);
            $label     = $this->relationLabel(array_column($bucket, 'rel'));
            $lines[]   = "{$primary['source']} \"{$sc}\" -- \"{$tc}\" {$primary['target']} : {$label}";
        }

        foreach ($morphEdges as $me) {
            $lines[] = "{$me['source']} .. * : {$me['rel']['method']} (morphTo)";
        }

        return $lines;
    }

    /**
     * Build a compact multi-line PlantUML label from one or more relation descriptors.
     */
    protected function relationLabel(array $rels): string
    {
        $parts = array_map(fn ($r) => "{$r['method']}\\n<<{$r['kind']}>>", $rels);
        return '"' . implode('\\n--\\n', $parts) . '"';
    }

    /**
     * Returns [sourceCardinality, targetCardinality] for a given relation kind.
     */
    protected function cardinalityFor(string $kind): array
    {
        return match ($kind) {
            'hasOne', 'hasOneThrough', 'morphOne'           => ['1', '0..1'],
            'hasMany', 'hasManyThrough', 'morphMany'        => ['1', '*'],
            'belongsTo'                                     => ['*', '1'],
            'belongsToMany', 'morphToMany', 'morphedByMany' => ['*', '*'],
            default                                         => ['1', '*'],
        };
    }

    protected function visibilitySymbol(string $visibility): string
    {
        return match ($visibility) {
            'public'    => '+ ',
            'protected' => '# ',
            'private'   => '- ',
            default     => '~ ',
        };
    }

    protected function escapeType(string $type): string
    {
        return str_replace(['<', '>'], ['{', '}'], $type);
    }
}
