<?php

namespace Quatrebarbes\Larchiclass\Generators;

use Quatrebarbes\Larchiclass\Analyzers\ClassAnalyzer;

class PlantUmlGenerator
{
    public function __construct(private readonly ClassAnalyzer $analyzer) {}

    /**
     * Generate a PlantUML diagram string from an array of analyzed class data.
     *
     * @param  array[]  $classes              Output of ClassAnalyzer::analyze()
     * @param  bool     $withVendor           When true, vendor classes are fully expanded
     * @param  bool     $keepRelationMethods  When true, relation methods are kept in class blocks
     */
    public function generate(array $classes, bool $withVendor = false, bool $keepRelationMethods = false): string
    {
        // Vendor stubs are still built so structural relations (extends/implements)
        // pointing to vendor classes can be resolved - but they are NOT rendered.
        $vendorExtras = $this->analyzer->buildVendorStubs($classes);
        $all          = array_merge($classes, $vendorExtras);

        $lines   = [];
        $lines[] = '@startuml';
        $lines[] = '';
        $lines[] = "' Generated by LarchiClass - " . now()->toDateTimeString();
        $lines[] = "' https://github.com/quatrebarbes/larchiclass";
        $lines[] = '';
        $lines[] = 'skinparam classAttributeIconSize 0';
        $lines[] = 'skinparam classFontStyle Bold';
        $lines[] = 'skinparam classBackgroundColor #F8F9FA';
        $lines[] = 'skinparam classBorderColor #6C757D';
        $lines[] = 'skinparam arrowColor #495057';
        $lines[] = 'skinparam groupInheritance 2';
        $lines[] = '';
        $lines[] = "' Stereotype styles";
        $lines[] = 'skinparam class {';
        $lines[] = '    BackgroundColor<<model>> #D8F3DC';
        $lines[] = '    BorderColor<<model>> #52B788';
        $lines[] = '}';
        $lines[] = '';
        $lines[] = 'hide empty members';
        $lines[] = '';

        // --- App classes only (vendor classes are never rendered) ---
        $appClasses = array_filter($all, fn ($c) => ! ($c['isVendor'] ?? false));
        if (! empty($appClasses)) {
            $lines[] = "' ── Application classes ─────────────────────────────";
            foreach ($appClasses as $class) {
                $lines[] = $this->renderClassBlock($class, $keepRelationMethods);
            }
        }

        // --- Inheritance / interface / trait relations ---
        // Only between app classes; vendor nodes are used for resolution only.
        $structuralRelations = $this->renderStructuralRelations($appClasses);
        if (! empty($structuralRelations)) {
            $lines[] = '';
            $lines[] = "' ── Structural relations (extends / implements / uses) ──";
            foreach ($structuralRelations as $rel) {
                $lines[] = $rel;
            }
        }

        // --- Eloquent relations ---
        $eloquentRelations = $this->renderEloquentRelations($all);
        if (! empty($eloquentRelations)) {
            $lines[] = '';
            $lines[] = "' ── Eloquent relationships ──────────────────────────";
            foreach ($eloquentRelations as $rel) {
                $lines[] = $rel;
            }
        }

        $lines[] = '';
        $lines[] = '@enduml';

        return implode(PHP_EOL, $lines) . PHP_EOL;
    }

    // -----------------------------------------------------------------------
    // Private helpers
    // -----------------------------------------------------------------------

    private function renderClassBlock(array $class, bool $keepRelationMethods = false): string
    {
        $lines = [];

        $isVendor  = $class['isVendor'] ?? false;
        $isStub    = $class['isStub'] ?? false;

        $keyword = match (true) {
            $class['isInterface'] => 'interface',
            $class['isTrait']     => 'class',
            $class['isAbstract']  => 'abstract class',
            $class['isEnum']      => 'enum',
            default               => 'class',
        };

        $stereotypes = [];
        if ($class['isTrait'])              $stereotypes[] = '<<trait>>';
        if ($class['isEloquent'] ?? false)  $stereotypes[] = '<<model>>';
        if ($isVendor)                      $stereotypes[] = '<<vendor>>';
        $stereotype = $stereotypes ? ' ' . implode(' ', $stereotypes) : '';

        $shortName = $class['name'];
        $lines[]   = "{$keyword} {$shortName}{$stereotype} {";

        if (! $isStub) {
            // Properties
            foreach ($class['properties'] as $prop) {
                $visibility = $this->visibilitySymbol($prop['visibility']);
                $static     = $prop['static'] ? '{static} ' : '';
                $type       = $prop['type'] ? ' : ' . $this->escapeType($prop['type']) : '';
                $lines[]    = "    {$visibility}{$static}{$prop['name']}{$type}";
            }

            if (! empty($class['properties']) && ! empty($class['methods'])) {
                $lines[] = '    --';
            }

            // Methods - filter out relation methods unless --keep-relation-methods
            $relationMethodNames = $class['relationMethods'] ?? [];
            $methods = $keepRelationMethods
                ? $class['methods']
                : array_filter(
                    $class['methods'],
                    fn ($m) => ! in_array($m['name'], $relationMethodNames, true)
                );

            foreach ($methods as $method) {
                $visibility = $this->visibilitySymbol($method['visibility']);
                $static     = $method['static'] ? '{static} ' : '';
                $abstract   = $method['abstract'] ? '{abstract} ' : '';
                $params     = implode(', ', array_map(fn ($p) => $this->escapeType($p), $method['params']));
                $return     = $method['return'] ? ' : ' . $this->escapeType($method['return']) : '';
                $lines[]    = "    {$visibility}{$abstract}{$static}{$method['name']}({$params}){$return}";
            }
        }

        $lines[] = '}';
        $lines[] = '';

        return implode(PHP_EOL, $lines);
    }

    private function renderStructuralRelations(array $classes): array
    {
        $lines      = [];
        $classNames = array_column($classes, 'name', 'fqcn');

        foreach ($classes as $class) {
            $shortName = $class['name'];

            // Inheritance
            if ($class['parent'] && isset($classNames[$class['parent']])) {
                $parentShort = $classNames[$class['parent']];
                $lines[]     = "{$parentShort} <|-- {$shortName}";
            }

            // Interface implementation - only if the interface is in our set
            foreach ($class['interfaces'] as $iface) {
                if (isset($classNames[$iface])) {
                    $ifaceShort = $classNames[$iface];
                    $lines[]    = "{$ifaceShort} <|.. {$shortName}";
                }
            }

            // Trait usage - only if the trait is in our set
            foreach ($class['traits'] as $trait) {
                if (isset($classNames[$trait])) {
                    $traitShort = $classNames[$trait];
                    $lines[]    = "{$traitShort} <.. {$shortName} : <<uses>>";
                }
            }
        }

        return $lines;
    }

    /**
     * Render Eloquent relationship arrows, merging reciprocal pairs into one link.
     *
     * When two models declare inverse relations to each other (e.g. User hasMany Post
     * and Post belongsTo User), a single arrow is emitted with both labels stacked,
     * and the cardinality is taken from the "has" side (the authoritative side).
     *
     * PlantUML arrow legend:
     *   hasOne / hasOneThrough     →  "1" – "0..1"
     *   hasMany / hasManyThrough   →  "1" – "*"
     *   belongsTo                  →  "*" – "1"
     *   belongsToMany              →  "*" – "*"
     *   morphOne                   →  "1" – "0..1"
     *   morphMany                  →  "1" – "*"
     *   morphTo                    →  dashed, polymorphic
     *   morphToMany / morphedByMany→  "*" – "*"
     */
    private function renderEloquentRelations(array $classes): array
    {
        $lines      = [];
        $classNames = array_column($classes, 'name', 'fqcn');

        // Build a reverse index: short name → canonical name in diagram
        $shortIndex = [];
        foreach ($classes as $c) {
            $shortIndex[$c['name']] = $c['name'];
        }

        // ── Step 1: collect all directed edges ───────────────────────────────
        // Each edge: ['source' => string, 'target' => string, 'rel' => array]
        $edges      = [];
        $morphEdges = [];   // morphTo has no reciprocal, handled separately

        foreach ($classes as $class) {
            $sourceName = $class['name'];

            foreach ($class['relations'] ?? [] as $rel) {
                if ($rel['kind'] === 'morphTo' || $rel['related'] === '*') {
                    $morphEdges[] = ['source' => $sourceName, 'rel' => $rel];
                    continue;
                }

                // Resolve target name inside the diagram
                $targetName = $rel['related'];
                if ($rel['relatedFqcn'] && isset($classNames[$rel['relatedFqcn']])) {
                    $targetName = $classNames[$rel['relatedFqcn']];
                }

                $edges[] = [
                    'source' => $sourceName,
                    'target' => $targetName,
                    'rel'    => $rel,
                ];
            }
        }

        // ── Step 2: group edges by unordered pair {A, B} ─────────────────────
        // Key = alphabetically sorted "ClassA|ClassB" so A→B and B→A share a bucket.
        $buckets = [];
        foreach ($edges as $edge) {
            $pair         = [$edge['source'], $edge['target']];
            sort($pair);
            $key          = implode('|', $pair);
            $buckets[$key][] = $edge;
        }

        // ── Step 3: emit one line per bucket ──────────────────────────────────
        foreach ($buckets as $edges) {
            if (count($edges) === 1) {
                $e     = $edges[0];
                [$sc, $tc] = $this->cardinalityFor($e['rel']['kind']);
                $label = $this->relationLabel([$e['rel']]);
                $lines[] = "{$e['source']} \"{$sc}\" -- \"{$tc}\" {$e['target']} : {$label}";
                continue;
            }

            $hasSideKinds = ['hasOne', 'hasMany', 'hasOneThrough', 'hasManyThrough',
                             'morphOne', 'morphMany', 'morphToMany', 'morphedByMany',
                             'belongsToMany'];

            $primary = collect($edges)->first(
                fn ($e) => in_array($e['rel']['kind'], $hasSideKinds, true)
            ) ?? $edges[0];

            [$sc, $tc] = $this->cardinalityFor($primary['rel']['kind']);
            $source    = $primary['source'];
            $target    = $primary['target'];
            $allRels   = array_column($edges, 'rel');
            $label     = $this->relationLabel($allRels);

            $lines[] = "{$source} \"{$sc}\" -- \"{$tc}\" {$target} : {$label}";
        }

        // ── Step 4: morphTo (polymorphic - no reciprocal possible) ────────────
        foreach ($morphEdges as $me) {
            $lines[] = "{$me['source']} .. * : {$me['rel']['method']} (morphTo)";
        }

        return $lines;
    }

    /**
     * Build a compact multi-line PlantUML label from one or more relation descriptors.
     * Each relation produces one line: methodName <<kind>>
     */
    private function relationLabel(array $rels): string
    {
        $parts = array_map(
            fn ($r) => "{$r['method']}\\n<<{$r['kind']}>>",
            $rels
        );

        // PlantUML uses \n inside quoted labels for line breaks
        return '"' . implode('\\n--\\n', $parts) . '"';
    }

    /**
     * Returns [sourceCardinality, targetCardinality] for a given relation kind.
     */
    private function cardinalityFor(string $kind): array
    {
        return match ($kind) {
            'hasOne', 'hasOneThrough', 'morphOne'              => ['1', '0..1'],
            'hasMany', 'hasManyThrough', 'morphMany'           => ['1', '*'],
            'belongsTo'                                        => ['*', '1'],
            'belongsToMany', 'morphToMany', 'morphedByMany'    => ['*', '*'],
            default                                            => ['1', '*'],
        };
    }

    private function visibilitySymbol(string $visibility): string
    {
        return match ($visibility) {
            'public'    => '+ ',
            'protected' => '# ',
            'private'   => '- ',
            default     => '~ ',
        };
    }

    private function escapeType(string $type): string
    {
        return str_replace(['<', '>'], ['{', '}'], $type);
    }

    private function shortName(string $fqcn): string
    {
        $parts = explode('\\', $fqcn);
        return end($parts);
    }
}
