<?php

namespace Quatrebarbes\Larchiclass\Analyzers;

use PhpParser\Node;
use PhpParser\Node\Expr\MethodCall;
use PhpParser\Node\Expr\StaticCall;
use PhpParser\Node\Stmt\ClassMethod;
use PhpParser\Node\Stmt\Function_;
use PhpParser\NodeTraverser;
use PhpParser\NodeVisitorAbstract;
use PhpParser\ParserFactory;

/**
 * Finds all call paths leading to a target method,
 * tracing back up to HTTP routes or Artisan commands.
 *
 * Works in three passes:
 *
 *  Pass 1 — repo scan → three indexes:
 *    - parentIndex  : FQCN => parent FQCN
 *    - methodIndex  : FQCN => [defined methods]
 *    - callIndex    : callee => [callers]   (explicit calls)
 *
 *  Between passes — injection of inheritance links:
 *    For each class C extending P, for each method M defined on P
 *    but NOT overridden by C, inject:
 *      callIndex[P::M] <- C::M   (synthetic inheritance link)
 *
 *  Pass 1b — route and Artisan command scan -> entryIndex:
 *    - routes/*.php    : Route::verb('/uri', [Ctrl::class, 'method'])
 *                        Route::verb('/uri', 'Ctrl@method')
 *                        Route::resource/apiResource('/uri', Ctrl::class)
 *    - commands        : classes extending Command, with $signature property
 *    Entry points are injected into callIndex as synthetic nodes
 *    "[HTTP GET /foo]" or "[CLI cmd:name]".
 *
 *  Pass 2 — DFS from target, walking back through callIndex -> full paths.
 *
 * Usage:
 *   $paths = CallAnalyzer::for('App\Http\Controllers\Controller', 'myMethod')->paths();
 *
 *   CallAnalyzer::for('App\Http\Controllers\Controller', 'myMethod')
 *       ->withinNamespace('App\Http')
 *       ->paths();
 *
 *   CallAnalyzer::for('App\Services\UserService', 'createUser')->entryPoints();
 *   // => ["HTTP POST /api/users", "CLI users:import"]
 */
class CallAnalyzer extends NodeVisitorAbstract
{
    // -- Config ------------------------------------------------------------

    private readonly string $targetClass;
    private readonly string $targetMethod;
    private ?string $namespaceFilter = null;

    // -- Visitor state (reset per file) ------------------------------------

    private string  $currentFile   = '';
    private string  $currentNs     = '';
    /** @var array<string, string> alias => FQCN */
    private array   $uses          = [];
    private string  $currentClass  = '';
    private ?string $parentClass   = null;
    private string  $currentCaller = '';
    /** @var array<string, string> varName => FQCN */
    private array   $varTypes      = [];

    // -- Global indexes ----------------------------------------------------

    /**
     * Direct inheritance: FQCN => parent FQCN.
     * @var array<string, string>
     */
    private array $parentIndex = [];

    /**
     * Methods defined (= declared in the body) per class.
     * FQCN => [methodName (lowercase), ...]
     * @var array<string, list<string>>
     */
    private array $methodIndex = [];

    /**
     * Inverted call index: callee => [caller, ...]
     * Contains explicit calls, inheritance links, and synthetic entry points.
     * @var array<string, list<string>>
     */
    private array $callIndex = [];

    /**
     * Metadata for callers(): callee => caller => [{file, line}]
     * @var array<string, array<string, list<array{caller: string, file: string, line: int}>>>
     */
    private array $callIndexMeta = [];

    /**
     * Synthetic inheritance links: child::method => parent::method
     * @var array<string, string>
     */
    private array $inheritedLinks = [];

    /**
     * HTTP/CLI entry points:
     *   FQCN::method => list<string>   (human-readable labels, e.g. "HTTP GET /api/users")
     * @var array<string, list<string>>
     */
    private array $entryIndex = [];

    private bool $indexed = false;

    // -- Supported HTTP verbs ----------------------------------------------

    private const ROUTE_VERBS = ['get', 'post', 'put', 'patch', 'delete', 'options', 'any', 'match'];

    /**
     * Implicit methods generated by Route::resource() / Route::apiResource().
     * @var array<string, string>  methodName => verb label
     */
    private const RESOURCE_METHODS = [
        'index'   => 'GET',
        'create'  => 'GET',
        'store'   => 'POST',
        'show'    => 'GET',
        'edit'    => 'GET',
        'update'  => 'PUT/PATCH',
        'destroy' => 'DELETE',
    ];

    private const API_RESOURCE_METHODS = [
        'index'   => 'GET',
        'store'   => 'POST',
        'show'    => 'GET',
        'update'  => 'PUT/PATCH',
        'destroy' => 'DELETE',
    ];

    // -- Construction ------------------------------------------------------

    private function __construct(string $targetClass, string $targetMethod)
    {
        $this->targetClass  = ltrim($targetClass, '\\');
        $this->targetMethod = strtolower($targetMethod);
    }

    public static function for(string $targetClass, string $targetMethod): self
    {
        return new self($targetClass, $targetMethod);
    }

    public function withinNamespace(string $prefix): self
    {
        $this->namespaceFilter = ltrim($prefix, '\\');
        return $this;
    }

    // -- Public entry points -----------------------------------------------

    /**
     * Returns all complete call stacks leading to the target method.
     * Root nodes may be "[HTTP GET /foo]" or "[CLI cmd:name]".
     * Each path is ordered from root to target.
     *
     * @return list<list<string>>
     */
    public function paths(): array
    {
        $this->buildIndex();

        $target = $this->targetClass . '::' . $this->targetMethod;
        $paths  = [];

        $this->dfs($target, [$target], [], $paths);

        foreach ($paths as &$path) {
            $path = array_reverse($path);
        }

        return $paths;
    }

    /**
     * Returns only the direct callers of the target method.
     *
     * @return list<array{caller: string, file: string, line: int}>
     */
    public function callers(): array
    {
        $this->buildIndex();

        $target  = $this->targetClass . '::' . $this->targetMethod;
        $results = [];

        foreach ($this->callIndex[$target] ?? [] as $caller) {
            foreach ($this->callIndexMeta[$target][$caller] ?? [] as $meta) {
                $results[] = $meta;
            }
        }

        return $results;
    }

    /**
     * Returns the synthetic inheritance links injected into the index.
     * Key   = child::method  (the child class that inherits without overriding)
     * Value = parent::method (the class that actually defines the method)
     *
     * @return array<string, string>
     */
    public function inheritedLinks(): array
    {
        $this->buildIndex();
        return $this->inheritedLinks;
    }

    /**
     * Returns the HTTP/CLI entry points that lead to the target method.
     * Walks all call stacks and collects labels of root nodes
     * of type "[HTTP ...]" or "[CLI ...]".
     *
     * @return list<string>  e.g. ["HTTP POST /api/users", "CLI users:import"]
     */
    public function entryPoints(): array
    {
        $paths   = $this->paths();
        $results = [];

        foreach ($paths as $path) {
            $root = $path[0];
            // Synthetic route/command nodes are enclosed in square brackets
            if (str_starts_with($root, '[') && str_ends_with($root, ']')) {
                $results[] = trim($root, '[]');
            }
        }

        return array_values(array_unique($results));
    }

    // -- Index building ----------------------------------------------------

    private function buildIndex(): void
    {
        if ($this->indexed) {
            return;
        }
        $this->indexed = true;

        // Pass 1: scan all PHP files
        $parser   = (new ParserFactory())->createForNewestSupportedVersion();
        $rootDirs = $this->resolveSourceDirs(base_path('composer.json'));

        foreach ($rootDirs as $dir) {
            if (!is_dir($dir)) {
                continue;
            }
            $iterator = new \RecursiveIteratorIterator(
                new \RecursiveDirectoryIterator($dir, \FilesystemIterator::SKIP_DOTS)
            );
            foreach ($iterator as $file) {
                /** @var \SplFileInfo $file */
                if (!$file->isFile() || $file->getExtension() !== 'php') {
                    continue;
                }
                $this->currentFile = $file->getPathname();
                $this->resetFileState();

                $ast       = $parser->parse(file_get_contents($file->getPathname()));
                $traverser = new NodeTraverser();
                $traverser->addVisitor($this);
                $traverser->traverse($ast);
            }
        }

        // Between passes: inject synthetic inheritance links
        $this->injectInheritanceLinks();

        // Pass 1b: scan routes and Artisan commands
        $this->buildEntryIndex();
    }

    /**
     * For each child class C extending P:
     * if P defines a method M that C does not override,
     * register C::M as a "caller" of P::M in the callIndex.
     */
    private function injectInheritanceLinks(): void
    {
        foreach ($this->parentIndex as $child => $parent) {
            $childMethods  = $this->methodIndex[$child]  ?? [];
            $parentMethods = $this->methodIndex[$parent] ?? [];

            $inheritedMethods = array_diff($parentMethods, $childMethods);

            foreach ($inheritedMethods as $method) {
                $callee = $parent . '::' . $method;
                $caller = $child  . '::' . $method;

                if (!in_array($caller, $this->callIndex[$callee] ?? [], true)) {
                    $this->callIndex[$callee][] = $caller;
                    $this->inheritedLinks[$caller] = $callee;
                    $this->callIndexMeta[$callee][$caller][] = [
                        'caller' => $caller,
                        'file'   => '[inherited]',
                        'line'   => 0,
                    ];
                }
            }
        }
    }

    // -- Pass 1b: routes and commands --------------------------------------

    /**
     * Pass 1b — builds entryIndex then injects synthetic nodes into callIndex.
     */
    private function buildEntryIndex(): void
    {
        $this->scanRouteFiles();
        $this->scanArtisanCommands();
        $this->injectEntryPointsIntoCallIndex();
    }

    /**
     * Scans routes/*.php and detects:
     *   Route::verb('/uri', [Ctrl::class, 'method'])
     *   Route::verb('/uri', 'Ctrl@method')
     *   Route::resource('/uri', Ctrl::class)
     *   Route::apiResource('/uri', Ctrl::class)
     */
    private function scanRouteFiles(): void
    {
        $routesDir = base_path('routes');
        if (!is_dir($routesDir)) {
            return;
        }

        $parser = (new ParserFactory())->createForNewestSupportedVersion();

        foreach (glob($routesDir . '/*.php') as $routeFile) {
            $ast = $parser->parse(file_get_contents($routeFile));

            $localUses    = [];
            $entryIndex   = &$this->entryIndex;
            $resourceMethods    = self::RESOURCE_METHODS;
            $apiResourceMethods = self::API_RESOURCE_METHODS;
            $routeVerbs   = self::ROUTE_VERBS;

            $traverser = new NodeTraverser();
            $traverser->addVisitor(
                new class(
                    $routeVerbs,
                    $resourceMethods,
                    $apiResourceMethods,
                    $localUses,
                    $entryIndex
                ) extends NodeVisitorAbstract {

                    public function __construct(
                        private readonly array $routeVerbs,
                        private readonly array $resourceMethods,
                        private readonly array $apiResourceMethods,
                        private array          &$uses,
                        private array          &$entryIndex,
                    ) {}

                    public function enterNode(Node $node): void
                    {
                        if ($node instanceof Node\Stmt\UseUse) {
                            $alias = $node->alias?->toString() ?? $node->name->getLast();
                            $this->uses[$alias] = $node->name->toString();
                        }

                        if (!$node instanceof StaticCall) {
                            return;
                        }
                        if (!$node->class instanceof Node\Name) {
                            return;
                        }
                        if (strtolower($node->class->getLast()) !== 'route') {
                            return;
                        }
                        if (!$node->name instanceof Node\Identifier) {
                            return;
                        }

                        $verb = strtolower($node->name->toString());
                        $args = $node->args;

                        if (count($args) < 2) {
                            return;
                        }

                        $uri = $args[0]->value instanceof Node\Scalar\String_
                            ? $args[0]->value->value
                            : '?';

                        // Route::resource() and Route::apiResource()
                        if ($verb === 'resource' || $verb === 'apiresource') {
                            $fqcn = $this->resolveClassConst($args[1]->value)
                                 ?? ($args[1]->value instanceof Node\Scalar\String_
                                     ? ltrim($args[1]->value->value, '\\')
                                     : null);
                            if ($fqcn === null) {
                                return;
                            }
                            $methods = $verb === 'apiresource'
                                ? $this->apiResourceMethods
                                : $this->resourceMethods;

                            foreach ($methods as $method => $httpVerb) {
                                $key = $fqcn . '::' . $method;
                                $this->entryIndex[$key][] = 'HTTP::' . $httpVerb . ' ' . $uri;
                            }
                            return;
                        }

                        // Standard verbs
                        if (!in_array($verb, $this->routeVerbs, true)) {
                            return;
                        }

                        $action = $args[1]->value;

                        // Array form: [Ctrl::class, 'method']
                        if ($action instanceof Node\Expr\Array_ && count($action->items) >= 2) {
                            $fqcn   = $this->resolveClassConst($action->items[0]->value);
                            $method = $action->items[1]->value instanceof Node\Scalar\String_
                                ? strtolower($action->items[1]->value->value)
                                : null;

                            if ($fqcn !== null && $method !== null) {
                                $key = $fqcn . '::' . $method;
                                $this->entryIndex[$key][] = 'HTTP::' . strtoupper($verb) . ' ' . $uri;
                            }
                            return;
                        }

                        // String form: 'Ctrl@method'
                        if ($action instanceof Node\Scalar\String_ && str_contains($action->value, '@')) {
                            [$class, $method] = explode('@', $action->value, 2);
                            $fqcn = $this->uses[$class] ?? $class;
                            $key  = ltrim($fqcn, '\\') . '::' . strtolower($method);
                            $this->entryIndex[$key][] = 'HTTP::' . strtoupper($verb) . ' ' . $uri;
                        }
                    }

                    private function resolveClassConst(Node\Expr $node): ?string
                    {
                        if (
                            $node instanceof Node\Expr\ClassConstFetch
                            && $node->class instanceof Node\Name
                            && $node->name instanceof Node\Identifier
                            && strtolower($node->name->toString()) === 'class'
                        ) {
                            $alias = $node->class->getLast();
                            $full  = $this->uses[$alias] ?? $node->class->toString();
                            return ltrim($full, '\\');
                        }
                        if ($node instanceof Node\Scalar\String_) {
                            return ltrim($node->value, '\\');
                        }
                        return null;
                    }
                }
            );

            $traverser->traverse($ast);
        }
    }

    /**
     * Walks the parentIndex to find all classes extending
     * (directly or indirectly) Illuminate\Console\Command,
     * then resolves their $signature.
     */
    private function scanArtisanCommands(): void
    {
        foreach (array_keys($this->parentIndex) as $fqcn) {
            if (!$this->isCommandClass($fqcn)) {
                continue;
            }

            $signature = $this->resolveCommandSignature($fqcn);
            if ($signature === null) {
                continue;
            }

            // Command name = first token of the signature (before spaces/options)
            $cmdName = explode(' ', trim($signature))[0];
            $key     = $fqcn . '::handle';

            $this->entryIndex[$key][] = 'CLI::' . $cmdName;
        }
    }

    /**
     * Walks the inheritance chain from $fqcn to detect
     * an ancestor whose short name is "Command".
     * Covers Illuminate\Console\Command and any intermediate subclass.
     */
    private function isCommandClass(string $fqcn): bool
    {
        $current = $fqcn;
        $seen    = [];

        while ($current && !isset($seen[$current])) {
            $seen[$current] = true;
            $short = class_basename($current);
            if (strtolower($short) === 'command') {
                return true;
            }
            $current = $this->parentIndex[$current] ?? null;
        }

        return false;
    }

    /**
     * Attempts to resolve the $signature property of an Artisan command.
     *
     * Strategy 1: PHP reflection (if the class is autoloadable).
     * Strategy 2: Re-scan the AST of the source file to extract the
     *             literal value of the $signature property.
     */
    private function resolveCommandSignature(string $fqcn): ?string
    {
        // Strategy 1 — reflection
        if (class_exists($fqcn)) {
            try {
                $ref  = new \ReflectionClass($fqcn);
                $prop = $ref->getProperty('signature');
                $prop->setAccessible(true);

                // Instantiate without dependencies (static property or class default)
                if ($prop->isStatic()) {
                    return $prop->getValue();
                }

                // Default value declared in the class
                $defaults = $ref->getDefaultProperties();
                if (isset($defaults['signature'])) {
                    return (string) $defaults['signature'];
                }
            } catch (\Throwable) {
                // Fall through to strategy 2
            }
        }

        // Strategy 2 — AST
        return $this->extractSignatureFromAst($fqcn);
    }

    /**
     * Re-parses the class source file to extract the literal value
     * of the $signature property without instantiating the class.
     */
    private function extractSignatureFromAst(string $fqcn): ?string
    {
        $file = $this->findFileForClass($fqcn);
        if ($file === null || !is_readable($file)) {
            return null;
        }

        $parser = (new ParserFactory())->createForNewestSupportedVersion();
        $ast    = $parser->parse(file_get_contents($file));

        $signature = null;
        $shortName = class_basename($fqcn);

        $traverser = new NodeTraverser();
        $traverser->addVisitor(
            new class($shortName, $signature) extends NodeVisitorAbstract {
                private bool $inClass = false;

                public function __construct(
                    private readonly string $shortName,
                    public ?string          &$signature,
                ) {}

                public function enterNode(Node $node): void
                {
                    if ($node instanceof Node\Stmt\Class_) {
                        if ($node->name?->toString() === $this->shortName) {
                            $this->inClass = true;
                        }
                    }

                    if ($this->inClass && $node instanceof Node\Stmt\Property) {
                        foreach ($node->props as $prop) {
                            if (
                                $prop->name->toString() === 'signature'
                                && $prop->default instanceof Node\Scalar\String_
                            ) {
                                $this->signature = $prop->default->value;
                            }
                        }
                    }
                }

                public function leaveNode(Node $node): void
                {
                    if ($node instanceof Node\Stmt\Class_) {
                        $this->inClass = false;
                    }
                }
            }
        );

        $traverser->traverse($ast);

        return $signature;
    }

    /**
     * Attempts to locate the source file for a FQCN using PSR-4 mappings
     * from composer.json (heuristic resolution, without the autoloader).
     */
    private function findFileForClass(string $fqcn): ?string
    {
        $composerJson = base_path('composer.json');
        $json         = json_decode(file_get_contents($composerJson), true);
        $baseDir      = dirname($composerJson);

        foreach (['autoload', 'autoload-dev'] as $section) {
            foreach ($json[$section]['psr-4'] ?? [] as $ns => $paths) {
                $ns = rtrim($ns, '\\') . '\\';
                if (!str_starts_with($fqcn . '\\', $ns)) {
                    continue;
                }
                $relative = str_replace('\\', '/', substr($fqcn, strlen($ns)));
                foreach ((array) $paths as $path) {
                    $candidate = $baseDir . '/' . rtrim($path, '/') . '/' . $relative . '.php';
                    if (file_exists($candidate)) {
                        return $candidate;
                    }
                }
            }
        }

        return null;
    }

    /**
     * Injects entry points into callIndex as synthetic nodes.
     * "[HTTP GET /api/users]" becomes a "caller" of "App\Http\Controllers\UserCtrl::index".
     */
    private function injectEntryPointsIntoCallIndex(): void
    {
        foreach ($this->entryIndex as $callee => $labels) {
            foreach ($labels as $label) {
                $caller = $label;

                if (!in_array($label, $this->callIndex[$callee] ?? [], true)) {
                    $this->callIndex[$callee][] = $label;
                    $this->callIndexMeta[$callee][$label][] = [
                        'caller' => $label,
                        'file'   => '[route/command]',
                        'line'   => 0,
                    ];
                }
            }
        }
    }

    // -- Recursive DFS -----------------------------------------------------

    /**
     * @param string              $node      Current node (callee)
     * @param list<string>        $pathSoFar Path built so far (target -> root)
     * @param array<string, true> $visited   Nodes in the current path (cycle guard)
     * @param list<list<string>>  $paths     Accumulated results
     */
    private function dfs(string $node, array $pathSoFar, array $visited, array &$paths): void
    {
        $callers = $this->callIndex[$node] ?? [];

        if (empty($callers)) {
            $paths[] = $pathSoFar;
            return;
        }

        foreach ($callers as $caller) {
            if (isset($visited[$caller])) {
                $paths[] = array_merge(['[cycle] ' . $caller], $pathSoFar);
                continue;
            }

            $this->dfs(
                $caller,
                array_merge([$caller], $pathSoFar),
                $visited + [$caller => true],
                $paths,
            );
        }
    }

    // -- NodeVisitorAbstract -----------------------------------------------

    public function enterNode(Node $node): void
    {
        if ($node instanceof Node\Stmt\Namespace_) {
            $this->currentNs = $node->name?->toString() ?? '';
            $this->uses      = [];
        }

        if ($node instanceof Node\Stmt\UseUse) {
            $alias              = $node->alias?->toString() ?? $node->name->getLast();
            $this->uses[$alias] = $node->name->toString();
        }

        if ($node instanceof Node\Stmt\Class_) {
            $this->currentClass = $this->qualify($node->name->toString());
            $this->parentClass  = $node->extends
                ? $this->resolveName($node->extends->toString())
                : null;

            if ($this->parentClass !== null) {
                $this->parentIndex[$this->currentClass] = $this->parentClass;
            }

            $this->varTypes = [];
        }

        if ($node instanceof Node\Stmt\Property && $node->type instanceof Node\Name) {
            $resolved = $this->resolveName($node->type->toString());
            foreach ($node->props as $prop) {
                $this->varTypes[$prop->name->toString()] = $resolved;
            }
        }

        if ($node instanceof ClassMethod) {
            $methodName = strtolower($node->name->toString());
            $this->methodIndex[$this->currentClass][] = $methodName;

            $this->currentCaller = $this->currentClass . '::' . $methodName;
            $this->collectParamTypes($node->params);
        }

        if ($node instanceof Function_) {
            $prefix              = $this->currentNs ? $this->currentNs . '\\' : '';
            $this->currentCaller = $prefix . $node->name->toString() . '()';
            $this->collectParamTypes($node->params);
        }

        if ($node instanceof MethodCall && $node->name instanceof Node\Identifier) {
            $method = strtolower($node->name->toString());
            $type   = $this->resolveVarType($node->var);
            if ($type !== null && $this->isInFilteredNamespace()) {
                $this->recordCall(ltrim($type, '\\') . '::' . $method, $node->getLine());
            }
        }

        if ($node instanceof StaticCall && $node->name instanceof Node\Identifier) {
            $method = strtolower($node->name->toString());
            $type   = $this->resolveStaticClass($node->class);
            if ($type !== null && $this->isInFilteredNamespace()) {
                $this->recordCall(ltrim($type, '\\') . '::' . $method, $node->getLine());
            }
        }
    }

    public function leaveNode(Node $node): void
    {
        if ($node instanceof Node\Stmt\Class_) {
            $this->currentClass = '';
            $this->parentClass  = null;
        }
        if ($node instanceof ClassMethod || $node instanceof Function_) {
            $this->currentCaller = '';
        }
    }

    // -- Index recording ---------------------------------------------------

    private function recordCall(string $callee, int $line): void
    {
        $caller = $this->currentCaller ?: '(top-level)';

        if (!in_array($caller, $this->callIndex[$callee] ?? [], true)) {
            $this->callIndex[$callee][] = $caller;
        }

        $this->callIndexMeta[$callee][$caller][] = [
            'caller' => $caller,
            'file'   => $this->currentFile,
            'line'   => $line,
        ];
    }

    // -- PSR-4 source resolution -------------------------------------------

    /** @return string[] */
    private function resolveSourceDirs(string $composerJson): array
    {
        $json    = json_decode(file_get_contents($composerJson), true);
        $baseDir = dirname($composerJson);
        $dirs    = [];

        foreach (['autoload', 'autoload-dev'] as $section) {
            foreach (['psr-4', 'psr-0'] as $standard) {
                foreach ($json[$section][$standard] ?? [] as $ns => $paths) {
                    if ($this->namespaceFilter !== null) {
                        $ns = rtrim($ns, '\\');
                        if (
                            !str_starts_with($this->namespaceFilter, $ns)
                            && !str_starts_with($ns, $this->namespaceFilter)
                        ) {
                            continue;
                        }
                    }
                    foreach ((array) $paths as $path) {
                        $dirs[] = $baseDir . '/' . rtrim($path, '/');
                    }
                }
            }
            foreach ($json[$section]['classmap'] ?? [] as $path) {
                $dirs[] = $baseDir . '/' . rtrim($path, '/');
            }
        }

        return $dirs;
    }

    // -- Visitor helpers ---------------------------------------------------

    private function resetFileState(): void
    {
        $this->currentNs     = '';
        $this->uses          = [];
        $this->currentClass  = '';
        $this->parentClass   = null;
        $this->currentCaller = '';
        $this->varTypes      = [];
    }

    private function isInFilteredNamespace(): bool
    {
        if ($this->namespaceFilter === null) {
            return true;
        }
        return str_starts_with($this->currentNs, $this->namespaceFilter);
    }

    private function resolveVarType(Node\Expr $expr): ?string
    {
        if ($expr instanceof Node\Expr\Variable && is_string($expr->name)) {
            return match ($expr->name) {
                'this'  => $this->currentClass ?: null,
                default => $this->varTypes[$expr->name] ?? null,
            };
        }
        if ($expr instanceof Node\Expr\PropertyFetch
            && $expr->var instanceof Node\Expr\Variable
            && $expr->var->name === 'this'
            && $expr->name instanceof Node\Identifier
        ) {
            return $this->varTypes[$expr->name->toString()] ?? null;
        }
        return null;
    }

    private function resolveStaticClass(Node $class): ?string
    {
        if (!$class instanceof Node\Name) {
            return null;
        }
        return match (strtolower($class->toString())) {
            'self', 'static' => $this->currentClass ?: null,
            'parent'         => $this->parentClass,
            default          => $this->resolveName($class->toString()),
        };
    }

    /** @param Node\Param[] $params */
    private function collectParamTypes(array $params): void
    {
        foreach ($params as $param) {
            if (!$param->type instanceof Node\Name) {
                continue;
            }
            $resolved = $this->resolveName($param->type->toString());
            if ($param->var instanceof Node\Expr\Variable && is_string($param->var->name)) {
                $this->varTypes[$param->var->name] = $resolved;
            }
        }
    }

    private function qualify(string $name): string
    {
        if (str_starts_with($name, '\\')) {
            return ltrim($name, '\\');
        }
        return $this->currentNs ? $this->currentNs . '\\' . $name : $name;
    }

    private function resolveName(string $name): string
    {
        if (str_starts_with($name, '\\')) {
            return ltrim($name, '\\');
        }
        $parts = explode('\\', $name);
        if (isset($this->uses[$parts[0]])) {
            $parts[0] = $this->uses[$parts[0]];
            return implode('\\', $parts);
        }
        return $this->qualify($name);
    }
}
